version: 2.1
# Use a package of configuration called an orb.
orbs:
# Define the jobs we want to run for this project
jobs:
  create_infrastructure:
      docker: 
        - image: amazon/aws-cli
      steps: 
        - checkout
        - run:
            name: Create Cloud formation stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name MyStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1 
  
  configure_infrastructure:
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints: ["ad:c2:66:a2:29:e4:c1:6f:81:9c:61:31:fc:c9:3f:e6"]
        - run:
            name: Install Ansible
            command: |
             apk add --update ansible
             apk add --update openssh
             apk add --update tar
             apk add --update gzip
             pip3 install awscli
        - run:
            name: Run playbook and configure server
            command: |
              ansible-playbook -i inventory main-remote.yml

  smoke_test: 
      docker:
      - image: alpine:latest
      steps:
        - run: apk add --update curl
        - run:
            name: smoke test
            command: |
              URL = "https://blog.udacity.com/"
              if curl -s --head URL
              then
                return 0
              else
                return 1
              fi

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      #- create_infrastructure
      #- configure_infrastructure
      - smoke_test